#!/bin/bash

path=`dirname $0`
. ${path}/ofctl.fnc
. ${path}/ofctl.conf

table_id="0"

while getopts d:u:t:h OPT
do
    case $OPT in
	"d" )
	    dpid="${OPTARG}";;
	"u" )
	    url="${OPTARG}";;
	"t" )
	    if [ "${OPTARG}" = "meter" ] ; then
		set_flow aaa "meter"
	    elif [ "${OPTARG}" = "group" ] ; then
		set_flow bbb "group"
	    elif expr "${OPTARG}" : '[0-9]*' > /dev/null ; then
		set_flow xxx "table ${OPTARG}"
	    else
		echo 'Error: -t [table_id|"group"|"meter"]'
		exit 1
	    fi ;;
	"h" )
	    echo "Usage: $CMDNAME [-d DPID] [-u URL] [-t [table_id|table_type]]"
	    exit 0 ;;
	* )
	    echo "Usage: $CMDNAME [-d DPID] [-u URL] [-t [table_id|table_type]]" 1>&2
	    exit 1 ;;
    esac
done

shift `expr $OPTIND - 1`

if [ -s /dev/stdin -o -p /dev/stdin ]; then
    cat - | while read line
    do
	set_flow delete "${line}"
    done
else
    set_flow delete_strict "$1"
fi
